import Head from "next/head";
import { Inter } from "next/font/google";
import dynamic from "next/dynamic";
import Loading from "@/components/loading/Loading";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const Todolist = dynamic(() => import("./../components/list/page"), {
    loading: () => <Loading/>,
  });
  return (
    <>
      <Head>
        <title>todo list</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="main">
        <Todolist />
      </div>
    </>
  );
}
